build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/docker/custom-nginx"
      --dockerfile "${CI_PROJECT_DIR}/docker/custom-nginx/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/nginx:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
